version: "3.7"

networks:
  holdem-network:

services:
  front:
    container_name: front-node
    restart: always
    build:
      context: ./front
    ports:
      - 2137:2137
    networks:
      - holdem-network
  users:
    container_name: users-node
    restart: always
    build:
      context: ./users
    ports:
      - 6969:6969
    networks:
      - holdem-network
  users-db:
    container_name: users-db
    image: mongo:latest
    ports:
      - '27017:27017'
    networks:
      - holdem-network
  relations:
    container_name: relations-node
    restart: always
    build:
      context: ./relations
    ports:
      - 2138:2138
    networks:
      - holdem-network
  relations-db:
    container_name: relations-db
    image: mongo:latest
    ports:
      - '27018:27017'
    networks:
      - holdem-network
  accounts:
    container_name: accounts-node
    restart: always
    build:
      context: ./accounts
    ports:
      - 2139:2139
    networks:
      - holdem-network
  accounts-db:
    container_name: accounts-db
    image: mongo:latest
    ports:
      - '27019:27017'
    networks:
      - holdem-network